autwit:
  database: mongo

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/autwit_test

# SQL must be disabled for Mongo
  sql:
    init:
      mode: never

  jpa:
    open-in-view: false
