spring:
  context:
    initializer:
      classes: com.acuver.autwit.runner.AutwitProfileInitializer


autwit:
  resume:
    enabled: true
    poll-interval: 30000
    batch-size: 10
    max-retries: 3
    parallel: false
    thread-count: 1

  retry:
    max-retries: 3
    check-db-resume: truea

  runner:
    class: com.bjs.tests.runner.ClientCucumberRunner