autwit:
  adapter:
    kafka:
      enabled: true

kafka:
  bootstrapServers: localhost:9092
  groupId: autwit-runner

topics:
#  - ex. order-created
#  - ex. order-updated
#  - ex. shipment-created
#  - ex. hipment-delivered

  # Optional enterprise settings
  securityProtocol:
  saslMechanism:
  saslJaasConfig:
